[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run migrate && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "smartvet-callcenter-api"

[services.env]
PORT = "4600"
